# Generated by Django 3.1.7 on 2021-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='stack',
            field=models.CharField(choices=[('Front', 'Frontend'), ('Back', 'Backend'), ('Both', 'Both')], default='Select an option', max_length=20),
        ),
    ]
