# Generated by Django 3.1.7 on 2021-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_answers_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='db',
            field=models.CharField(choices=[('pg', 'PostgreSQL'), ('my', 'MySQL'), ('o', 'Oracle'), ('sqls', 'SQL Server')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='answers',
            name='exp',
            field=models.CharField(choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7+', '7+')], default='0', max_length=20),
        ),
    ]
