# Generated by Django 3.1.7 on 2021-03-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210321_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question3',
            new_name='years',
        ),
    ]
