# Generated by Django 3.1.7 on 2021-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210321_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='db',
            field=models.CharField(choices=[('none', 'None Selected'), ('pg', 'PostgreSQL'), ('my', 'MySQL'), ('o', 'Oracle'), ('sqls', 'SQL Server')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='exp',
            field=models.CharField(choices=[('none', 'None Selected'), ('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7+', '7+')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='stack',
            field=models.CharField(choices=[('none', 'None Selected'), ('Front', 'Frontend'), ('Back', 'Backend'), ('Both', 'Both')], default='none', max_length=20),
        ),
    ]
